defaults:
  - model: default
  - data: default
  - training: default
  - _self_

seed: 42
device: "auto"
experiment_name: "test_experiment"

data_dir: "./data"

dvc:
  remote_url: "https://drive.google.com/drive/folders/1zIjqdYP7n5hjffiKE0SSkYZuT_D5J49d?usp=sharing"
  use_dvc: true
  repo_path: "."  # Путь к корню DVC репозитория (относительно текущей директории)
  remote_name: "setcover_gnn_data"

logging:
  enabled: true
  backend: "mlflow"
  mlflow:
    tracking_uri: "http://127.0.0.1:8080"
    experiment_name: "setcover_experiments"
    run_name: "${experiment_name}"
    tags:
      test_run: "true"
      framework: "pytorch-lightning"

paths:
  log_dir: "./logs/test"
  output_dir: "./results/test"
  checkpoint_dir: "./checkpoints/test"
